version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    networks:
      - db_task
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: karthikeyansirpi/fastapi-task-app:latest
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    networks:
      - db_task
    ports:
      - "80:8000"   # better for production

volumes:
  postgres_data:

networks:
  db_task:
    driver: bridge